### ISSUE TITLE
Respect `hl-todo-mode`?

### ISSUE THREAD

**Issue by jcs090218** [alvarogonzalezsotillo/flycheck-hl-todo#1]
First thing first, awesome package! I love it! 🚀 😋 

I think the checker should respect whether `hl-todo-mode` is enabled/disabled. For example, if I disabled `hl-todo-mode`, then the flycheck should stop showing those error indicators, etc. 🤔

**Comment by alvarogonzalezsotillo** [comment]
I think it is more flexible to let the checker and `hl-todo-mode` be enabled independently.

If someone needs it, `hl-todo-mode` and the checker can be easily in sync with a snippet like:

```lisp
(defun flycheck-hl-todo-follow-mode ()
  (setq flycheck-hl-todo-enabled hl-todo-mode)
  ;; Force flycheck update
  (flycheck-buffer))

(add-hook 'hl-todo-mode-hook #'flycheck-hl-todo-follow-mode)
```

(I have added this snippet to the readme).

**Comment by jcs090218** [comment]
Thank you! That works too! :D
